name: 每日同步飞书数据

on:
  schedule:
    # 每天北京时间早上 8 点执行（UTC 时间 0 点）
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: 安装依赖
        run: npm install
        
      - name: 检查 Secrets
        run: |
          echo "检查 GitHub Secrets 是否已在仓库中设置..."
          if [ -z "${{ secrets.FEISHU_APP_ID }}" ]; then echo "警告：FEISHU_APP_ID 未设置"; fi
          if [ -z "${{ secrets.FEISHU_APP_SECRET }}" ]; then echo "警告：FEISHU_APP_SECRET 未设置"; fi
          if [ -z "${{ secrets.FEISHU_NODE_TOKEN }}" ]; then echo "警告：FEISHU_NODE_TOKEN 未设置"; fi
          if [ -z "${{ secrets.FEISHU_TABLE_ID }}" ]; then echo "警告：FEISHU_TABLE_ID 未设置"; fi
          if [ -z "${{ secrets.FEISHU_VIEW_ID }}" ]; then echo "警告：FEISHU_VIEW_ID 未设置"; fi
          
      - name: 执行同步脚本
        run: node scripts/sync-feishu.js
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          FEISHU_NODE_TOKEN: ${{ secrets.FEISHU_NODE_TOKEN }}
          FEISHU_TABLE_ID: ${{ secrets.FEISHU_TABLE_ID }}
          FEISHU_VIEW_ID: ${{ secrets.FEISHU_VIEW_ID }}
          FEISHU_DAILY_TABLE_ID: ${{ secrets.FEISHU_DAILY_TABLE_ID }}
          FEISHU_OBJ_TYPE: ${{ secrets.FEISHU_OBJ_TYPE }}
          
      - name: 提交更改
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add public/content-data.json
          git commit -m "自动同步飞书数据 $(date +'%Y-%m-%d')" || echo "没有变更需要提交"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
